name: Process Excel Files

on:
  push:
    paths:
      - 'inputs/**'  # Trigger when files are added to the inputs folder

jobs:
  process-excel:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas openpyxl

      # Run the Python script
      - name: Process Excel files
        run: |
          python scripts/process_excel.py

      # Commit and push the output files
      - name: Commit and push output files
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add outputs/
          git commit -m "Added processed Excel files"
          git push
